# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20160826_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created_at',), 'verbose_name': 'Title'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.User'),
        ),
    ]
