# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20160828_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='user'),
        ),
    ]
