# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20160823_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic', verbose_name='Topic'),
        ),
    ]
