# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20160824_1204'),
        ('topics', '0003_auto_20160822_1609'),
    ]

    operations = [
    ]
