# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 8, 25, 9, 57, 21, 327057, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic', verbose_name='Topic'),
        ),
    ]
