# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20160829_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserJunior',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('entry', 'user')]),
        ),
    ]
