# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_auto_20160829_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjunior',
            name='junior',
            field=models.BooleanField(default=True),
        ),
    ]
