# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_auto_20160829_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserJunior',
            new_name='User',
        ),
    ]
