# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-26 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_auto_20160830_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created_at',), 'verbose_name': 'Topic'},
        ),
    ]
